server:
  port: 18761
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 1000

