
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/

mybatis:
  typeAliasesPackage: com.client.eurekaclient.pojo
  mapperLocations: classpath:mapper/*.xml


server:
  port: 18762
spring:
  application:
    name: service-hi1
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123
